version: "3.7"
services:
  selenium:
    # @see
    #   - https://github.com/elgalu/docker-selenium
    #   - https://hub.docker.com/r/elgalu/selenium/
    #   - https://knowledge.sakura.ad.jp/2631/
    image: elgalu/selenium
    extra_hosts:
      - localhost:192.168.33.10
  app:
    stdin_open: true
    tty: true
    build: .
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle
    command: sh -c "bundle && /bin/sh"
    depends_on:
      - selenium
volumes:
  bundle_data:
